language: python
python:
  - 3.8
services:
  - docker
  - postgresql
before_install:
  - echo 'DJANGO_SECRET_KEY = '$DJANGO_SECRET_KEY >> .env
  - echo 'DB_NAME = '$DB_NAME >> .env
  - echo 'DB_USER = '$DB_USER >> .env
  - echo 'DB_PASSWORD = '$DB_PASSWORD >> .env
  - echo 'DB_HOST = '$DB_HOST >> .env
install:
  - pip install -r backend/requirements.txt
script:
  - docker-compose build
  - docker-compose run web python backend/manage.py migrate
  - docker-compose run web python backend/manage.py test